const config = {
    style: "mapbox://styles/dylanmaxwell/ckq7g8e1k2rhr17llm91ytvp5",
    accessToken: "pk.eyJ1IjoiZHlsYW5tYXh3ZWxsIiwiYSI6ImNrcTczNGtzNTAwcDYyb3BtdGN3em5ndGsifQ.df72_vr_4lG4QTdcwlXa-g",
    CSV: "./UNIDOS_Affiliates_TEST.csv",
    center: [-96.164, 38.351],
    zoom: 4,
    title: "UNIDOS Affiliate Map",
    description: "",
    sideBarInfo: ["affiliate_name", "address", "website"],
    popupInfo: ["affiliate_name"],
    filters: [{
            type: "dropdown",
            title: "Affiliate Funding: ",
            columnHeader: "Value",
            listItems: [
                "Under $500k ($731.57)",
                "$500K -$1M ($1,043.34)",
                "$1 - $2.5M ($1,217.23)",
                "$2.5 - $5M ($1,391.13)",
                "$5 - $10M ($1,622.98)",
                "$10 - $25M ($2,318.54)",
                "Over $25M ($2,903.32)",
            ],
        },
        {
            type: "checkbox",
            title: "Group Info: ",
            columnHeader: "group", // Case sensitive - must match spreadsheet entry
            listItems: ["Group A (FY18)", "Group B (FY19)", "Group C (FY20)", "None"], // Case sensitive - must match spreadsheet entry; This will take up to six inputs but is best used with a maximum of three;
        },
        {
            type: "dropdown",
            title: "UNIDOS Affiliate Issues: ",
            columnHeader: "issue_area",
            listItems: [
                "Advocacy & Empowerment",
                "Civic Engagement",
                "Civil Rights & Racial Justice",
                "Juvenile Justice",
                "Legal Services",
                "Leadership Development",
                "Research & Advocacy",
                "State & Local Advocacy",
                "Federal Advocacy",
                "Health Policy & Advocacy (Access, nutrition, & mental health)",
                "Economic Policy & Advocacy (Financial & Housing)",
                "Education Policy & Advocacy (Higher Ed, K-12 and ECE)",
                "Immigration Policy & Advocacy (Public charge, DACA, TPS)",
                "Voter Registration/ GOTV",
                "Engaged in Policy & Advocacy Work",
                "Banking & Financial Services",
                "Community Development Financial Insitution (CDFI)",
                "Economy & Workforce",
                "Economic Mobility",
                "Emergency Preparedness",
                "Housing/ Property Management",
                "Homeownership Programs/Counseling",
                "Volunteer IncomeTax Assistance (VITA)",
                "Wealth Building",
                "HUD Approved Housing Counseling Agency",
                "Charter School",
                "Early Childhood Education",
                "Head Start",
                "K-12 Education",
                "After School Programs",
                "Summer School Programs",
                "College Preparation",
                "Parent Engagement",
                "Primary Medical Care",
                "Federally Qualified Health Center",
                "Engaged in Health work",
                "Immigration Referrals",
                "LGBTQ Programs",
                "Digital Literacy",
                "None",
            ],
        },
    ],
};