const config = {
    style: "mapbox://styles/dylanmaxwell/ckq7g8e1k2rhr17llm91ytvp5",
    accessToken: "pk.eyJ1IjoiZHlsYW5tYXh3ZWxsIiwiYSI6ImNrcTczNGtzNTAwcDYyb3BtdGN3em5ndGsifQ.df72_vr_4lG4QTdcwlXa-g",
    CSV: "https://docs.google.com/spreadsheets/d/1UXT6L0Da3_R77fEn-BqWDSQPCIDKc2sd6cOYoWgxwjE/gviz/tq?tqx=out:csv&sheet=Sheet1",
    center: [-96.164, 38.351],
    zoom: 3.5,
    title: "",
    description: "Click the Affiliate points on the map for more details. Filter Affiliate issue areas by clicking the button below.",
    sideBarInfo: ["affiliate_name"],
    popupInfo: ["affiliate_name"],
    filters: [{
        type: "checkbox",
        title: "UNIDOS Affiliate Issues: ",
        columnHeader: "issue_area",
        listItems: [
            "Advocacy & Empowerment",
            "Civic Engagement",
            "Civil Rights & Racial Justice",
            "Juvenile Justice",
            "Legal Services",
            "Leadership Development",
            "Research & Advocacy",
            "State & Local Advocacy",
            "Federal Advocacy",
            "Health Policy & Advocacy (Access, nutrition, & mental health)",
            "Economic Policy & Advocacy (Financial & Housing)",
            "Education Policy & Advocacy (Higher Ed, K-12 and ECE)",
            "Immigration Policy & Advocacy (Public charge, DACA, TPS)",
            "Voter Registration/ GOTV",
            "Engaged in Policy & Advocacy Work",
            "Banking & Financial Services",
            "Community Development Financial Insitution (CDFI)",
            "Economy & Workforce",
            "Economic Mobility",
            "Emergency Preparedness",
            "Housing/ Property Management",
            "Homeownership Programs/Counseling",
            "Volunteer IncomeTax Assistance (VITA)",
            "Wealth Building",
            "HUD Approved Housing Counseling Agency",
            "Charter School",
            "Early Childhood Education",
            "Head Start",
            "K-12 Education",
            "After School Programs",
            "Summer School Programs",
            "College Preparation",
            "Parent Engagement",
            "Primary Medical Care",
            "Federally Qualified Health Center",
            "Engaged in Health work",
            "Immigration Referrals",
            "LGBTQ Programs",
            "Digital Literacy",
            "None",
        ],
    }],
};